### ISSUE TITLE
Problem with RFID module

### ISSUE THREAD

**Issue by thierry7100** [technologiescollege/Blockly-at-rduino#107]
Hi,

I found a problem with the block RFID_valeur_cle. The function associated with this block returns a boolean, it should return a string (TEXT in blockly).
I have made the change in my local copy of Blockly@rduino and it seems working fine.

**Comment by SebCanet** [comment]
Hi, correction online now. Thanks.

**Comment by thierry7100** [comment]
Thanks a lot for the prompt correction.
One more minor glitch : item RFID_lecture_cle_TEXT  and RFID_reception_cle_TOOLTIP are in French even when Blockly is configured in English. Not a problem for me as I am French native speaker but this should improve this great project.

**Comment by SebCanet** [comment]
Corrected, thanks !
