### ISSUE TITLE
Problem with I2C Scanner (at least in LCD Module).

### ISSUE THREAD

**Issue by thierry7100** [technologiescollege/Blockly-at-rduino#110]
Arduino code for I2C scan is not correct. Strings to be printed on console are enclosed between simple quote (') instead of double quotes (").
So the console output is not correct

Generated code

  Wire.begin();
  for (byte i = 8; i < 120; i++)
    {
	 Wire.beginTransmission (i);
	 if (Wire.endTransmission () == 0)
	   {
	   Serial.print ('Found address: ');
	   Serial.print (i, DEC);
	   Serial.print (' (0x');
	   Serial.print (i, HEX);
	   Serial.println (')');
	   count++;
	   delay (1);
	   } // end of good response
    } // end of for loop
  Serial.println ('Done.');
  Serial.print ('Found ');
  Serial.print (count, DEC);
  Serial.println (' device(s).');

**Comment by SebCanet** [comment]
Tanhks, I think that's ok now.
Tell me if you see another bug.
