### ISSUE TITLE
Fonctionnement en interruption

### ISSUE THREAD

**Issue by jbet** [technologiescollege/Blockly-at-rduino#12]
Voici comment le compilateur accepte le fonctionnement en interruption.
Les modification à apporter sont :
Mettre la fonction
 attachInterrupt(2,attachInterrupt_2,RISING); 
 dans le setup, c'est plus logique

![selection_161](https://cloud.githubusercontent.com/assets/5906988/14227658/ef7f6d86-f902-11e5-89db-4b1062031239.png)

De plus la fonction :
digitalPintoInterrup(  ), doit rester en commentaire, et ne passer que le numéro de la broche qui sera utilisé en interruption.
J'ai fait le tour de plusieurs sites, et cela confirme l'erreur qu'il y a sur le site Arduino.
Enfin la variable qui sera utilisée dans l'interruption doit être de type *_volatile int *_variable, afin que l'on puisse utiliser cette variable dans les différentes fonctions.

Voici ce que l'on devrait obtenir

volatile int codeur_gauche;
void attachInterrupt_2() {
  codeur_gauche = codeur_gauche  + 1;
}
void setup() {
  pinMode(2, INPUT);
  attachInterrupt(2,attachInterrupt_2,RISING);
}

void loop() {

}

ET QUAND LE FONCTIONNEMENT EN INTERRUPTION FONCTIONNERA, ON POURRA L'UTILISER POUR LE MODULE BLUETOOTH (RX en interruption)
BON COURAGE.

**Comment by SebCanet** [comment]
Docs à approfondir ::
[https://www.arduino.cc/en/Reference/AttachInterrupt](https://www.arduino.cc/en/Reference/AttachInterrupt)
[http://www.mon-club-elec.fr/pmwiki_reference_arduino/pmwiki.php?n=Main.Volatile](http://www.mon-club-elec.fr/pmwiki_reference_arduino/pmwiki.php?n=Main.Volatile)

**Comment by SebCanet** [comment]
Volatile int included in type definition.
