### ISSUE TITLE
Firmata

### ISSUE THREAD

**Issue by jbet** [technologiescollege/Blockly-at-rduino#14]
Dans Blockly@rduino, il y a un dossier Firmata.
Est ce Blockly@rduino est compatible avec Firmata !
Y a t il une doc pour savoir comment l'utiliser ?
J'ai vu comment installer Firmata+, sur youtube

A plus

**Comment by SebCanet** [comment]
Il n'y a pas de dossier Firmata ??!
il n'y a pas de 'compatibilité' car ton programme remplace celui chargé dans la mémoire de la carte (ex : Firmata). Mais si tu téléverses FirmataPlus dans la carte, l'onglet supervision devient utilisable.

**Comment by jbet** [comment]
Bien, merci pour la réponse sur Firmata, je vais essayer.

Pour info, car je pense que tu le sais, on ne peut plus accéder au site.

J'aurais une demande :
1 Implanté une possibilité #define..., je te précise demain ce que j'ai en tête...

Mais quand je vois les dates dépôts sur le site Github, il faut dormir de temps en temps, ou alors tu es très fort...

Bon courage.

----- Mail original -----
De: "SebCanet" notifications@github.com
À: "technologiescollege/Blockly-at-rduino" Blockly-at-rduino@noreply.github.com
Cc: "jbet" jb.etieve@free.fr
Envoyé: Lundi 4 Avril 2016 20:15:06
Objet: Re: [technologiescollege/Blockly-at-rduino] Firmata (#14)

Il n'y a pas de dossier Firmata ??! 
il n'y a pas de 'compatibilité' car ton programme remplace celui chargé dans la mémoire de la carte (ex : Firmata). Mais si tu téléverses FirmataPlus dans la carte, l'onglet supervision devient utilisable.
