### ISSUE TITLE
Problem with RFID module

### ISSUE THREAD

**Issue by thierry7100** [technologiescollege/Blockly-at-rduino#146]
Hi,

I have some problem with the RFID module. This module use a very old RFID library which in my case doesn't work very well with all modules. 
I have used this library with 5 boards from arduino kits and the code worked only with two boards. I have replaced the RFID library with the newer MFRC522 library and the code worked fine with the 5 boards.
I have added a new MFRC522 module to my copy of blockly@duino and if interested I would like to share my code. In this case, how am I able to do it ?

Thanks in advance

**Comment by SebCanet** [comment]
Well I don't know... If you think RFID.h is deprecated and we should change to new MFRC522, no problem.
You can commit your work via Git, or just use the lastest Blockly@rduino to put in your modification and send it.

**Comment by SebCanet** [comment]
It's updated.
