### ISSUE TITLE
Bloc define

### ISSUE THREAD

**Issue by jbet** [technologiescollege/Blockly-at-rduino#15]
La définition d'une variable nous permet de racrrocher à une variable une instruction.
Exemple : #define LED1_allumée digitalWrite( LED, High)
Quand le compilateur rencontre LED_allumée, il substitue LED_allumée par digitalWrite( LED, High). Et cela devient alors beaucoup plus facile pour des élèves grands débutants  en algorithmes.

Pourriez vous faire, 2 blocks spécifiques, en s'inspirant de ce qui existe ;

Le premier pour des informations en entrées du microcontrôleur :

![selection_168](https://cloud.githubusercontent.com/assets/5906988/14311463/efd136a6-fbe7-11e5-9b92-ff1bab02ca4d.png)

Qui se lira
Définir BP1 comme étant l'état logique de la broche numérique ( numéro, ou nom de variable), et
tout ceci en un seul bloc.
La broche numérique sera aussi mise en entrées ( INPUT), et ce bloque pourra être mis dans les testes ( en SI... )

Le second pour des informations en sorties du microcontrôleur :
![selection_169](https://cloud.githubusercontent.com/assets/5906988/14311571/6501263e-fbe8-11e5-8480-248bfbb20ddb.png)

Sur le dessin, j'ai mis la variable, LED1_allumée.
C'est donc la même chose que le point 1, crée un Défine pour les sorties, mais avec une information supplémentaire, l'état de la sortie.
De plus, le bloc LED1_allumée, devra se mette dans les actions.
La broche numérique sera aussi mise en sortie.

Ce qui nous donnera en final
![selection_170](https://cloud.githubusercontent.com/assets/5906988/14311643/aeb96f66-fbe8-11e5-8f91-d0c4b6449a56.png)

Et en final, l'algorithme se résumera à l'image ci dessus.
Le professeur font les define qui seront dans le Setup, et les élèves architecturent tout ceci.

Et si en plus on utilise Firmata, alors ...

Ensuite, il faudra voir pour les signaux analogiques...

Bon courage

**Comment by bmcage** [comment]
This is bad practice. In my view, kids must learn correct paradigms.

My approach you see here: http://ingegno.be/Manuals/Blockly4Arduino/blockly4Arduino/index_en.html?url=examples/Blink.xml

You can also change the generic digital output block, by a LED block. Then kids can just use a block: put LED on and put LED off. See this used in example Blink No Delay.
Note that coding with No Delay is easy with the effect block, but the code is then advanced coding level!

**Comment by SebCanet** [comment]
I totally agree with you bmcage, I think it's confusing algorithm and program.
For younger novice, I created a multi level toolbox to choose what kind of details you allow, it can help for very new user but not really a practice to keep. It's not very difficult to make understandable 'function' utility.
