### ISSUE TITLE
Problem with pins  defined as INPUT_PULLUP

### ISSUE THREAD

**Issue by thierry7100** [technologiescollege/Blockly-at-rduino#150]
Hi,

I use pins with INPUT_PULLUP to avoid cabling some resistors...
But the code generated is incorrect, see example below. The pin is declared as INPUT_PULLUP as requested, but this definition is followed by a declaration as INPUT which is added when I use a digitalRead with this pin. As this is the second declaration, the first one is overridden.

void setup() {
    pinMode(4, INPUT_PULLUP);

  pinMode(4, INPUT);
  pinMode(13, OUTPUT);
}

void loop() {
    if (digitalRead(4)) {
      digitalWrite(13, HIGH);

    }

}

**Comment by SebCanet** [comment]
Hi,
I think it's ok with my last upload.
thanks for checking.
