### ISSUE TITLE
English Translations

### ISSUE THREAD

**Issue by adamdrenth** [technologiescollege/Blockly-at-rduino#151]
The English version of Blockly@rdunio seems to have a fair amount of French in the blocks and examples.  Is there someone already working on translating it completely.  In the brief look over the code, there is a fair amount in lang/BlocklyArduino_blocks/en.js.  

I would be interested in helping update this though I will admit this is my first crack at an open project on Github.  Please let me know if someone else in the community is already working on the issue. If no one is working on this, I am assuming I need to branch and then send in a pull request.

**Comment by SebCanet** [comment]
Hi,
as many contributors are French teachers, we often do fast and try with kids...and forget to add translation if it's not added at the block creation. Sorry.

I also tried to create multilingual wiki, but I can found no time to update it regularly, and it's worth in english: [http://www.libreduc.cc/wiki/doku.php](http://www.libreduc.cc/wiki/doku.php)

That's a very kind proposal, thanks a lot! If you can help and fix my tanslation lack, that would be perfect.
