### ISSUE TITLE
Buttons don't display properly

### ISSUE THREAD

**Issue by adamdrenth** [technologiescollege/Blockly-at-rduino#152]
I am unable to see several import buttons that are hidden behind the main code view.  I'm using Chrome and only see the tops of buttons under the 1 2 3 4 tout buttons.  I also added a few libraries for Capacitive Sensor, LCD, Servo and LCD Screens.

**Comment by SebCanet** [comment]
Hi, there's a pb with Chrome: [http://www.chrome-allow-file-access-from-file.com/](http://www.chrome-allow-file-access-from-file.com/)
If you know how to resolve, I could have a look again.
But now you should use Firefox.
