### ISSUE TITLE
Game Menu

### ISSUE THREAD

**Issue by tarbear123** [technologiescollege/Blockly-at-rduino#154]
Can you create a menu for a lcd screen?

**Comment by SebCanet** [comment]
Hi,
there's already a "LCD screen" menu. You choose expert level for "Configure block" and you have one with different LCD screen from diferent categories.
Is that what you want?

**Comment by tarbear123** [comment]
no like i want to create a menu on a led screen for a project, how would i create the menu in the program?

**Comment by SebCanet** [comment]
Well I think it's quite long....
You have to define every entence in your program and then add test to change viewed sentence, no automatic tools, sorry.
