### ISSUE TITLE
requesting your aid

### ISSUE THREAD

**Issue by tarbear123** [technologiescollege/Blockly-at-rduino#155]
why is it that when i set the language to English, some of the words on the blocks are still french (secrete blocks in a category) and i downloaded the file but how do i include it into Block@rduino

**Comment by SebCanet** [comment]
Because sometime people who created block forget to translate it, or maybe when I do it in hurry for my student I first type french sentences inside and after (when it works) I add english translation.
Do you want to help tanslate ?
