### ISSUE TITLE
.md please in english

### ISSUE THREAD

**Issue by ghost** [technologiescollege/Blockly-at-rduino#164]
Hey :-)
First of all, thank you very much for this awesome tool.
But as I wrote in the title, can you please provide all important information in english?
Since we are in a international environment in the web, projects like this (or all kind of IT-/programming related projects) are usually in english, with this project also should be better to provide all important information in english.
I can't learn another language only to understand the installation instructions or how it work and so on... you know?
Please don't provide a tool to make programming easy while blocking people from using it with mixing languages.

**Comment by SebCanet** [comment]
Hi,
a mistake...a wrong upload destroyed my multilingual version of README. It's fixed.
Thanks.
