### ISSUE TITLE
Operator preceence issue

### ISSUE THREAD

**Issue by thierry7100** [technologiescollege/Blockly-at-rduino#168]
At least with modulo operation operators' precedence is not respected.
If I create a block with the following block
![TestBlocly](https://user-images.githubusercontent.com/35993911/84923615-b7fccd00-b0c7-11ea-97c4-02980298ccf5.png)
 The generated code is 
`  Test = 6 + 7 % 13;`
which is incorrect, there are missing parenthesis around 6 + 7

**Comment by SebCanet** [comment]
Thanks, fixed!
