### ISSUE TITLE
Erreur avec "mettre la variable à 10" version 18-04-2016 

### ISSUE THREAD

**Issue by YannChavria** [technologiescollege/Blockly-at-rduino#19]
Il semble y avoir un bug avec le générateur de code du bloc **mettre variable à**. 

voici le code:
![blocks_erreur_variable](https://cloud.githubusercontent.com/assets/17923922/15069426/c3440da4-137d-11e6-80da-7f4bb557e5b0.PNG)

Le message d'erreur généré lorsque que l'on va sur l'onglet **code Arduino**:
![variable_ messageerreur](https://cloud.githubusercontent.com/assets/17923922/15069453/f39fcd6c-137d-11e6-92e1-d2db3a4c54ca.PNG)

> TypeError: nextBlock.inputList[0].connection is 

Et le contournement du problème(cast obligatoire):
![blocks_erreur_variable_workaround](https://cloud.githubusercontent.com/assets/17923922/15069470/1e04a5f0-137e-11e6-8ecb-93ae25043cb5.PNG)

**Comment by SebCanet** [comment]
Il ne s'agit pas d'un contournement mais du fonctionnement pour l'instant, bientôt une fois le typage effectué il restera effectif sans voir besoin de typer chaque valeur.
