### ISSUE TITLE
**temps écoulé depuis le début du programme** inutilisable plus de 30s

### ISSUE THREAD

**Issue by YannChavria** [technologiescollege/Blockly-at-rduino#20]
Je n'ai pas réussi à déclarer et à utiliser une variable de type **unsigned long**, ce qui fait que je ne peux pas stocker la valeur du bloc **temps écoulé depuis le début du programme**.

L'utilité de ce bloc sans variable **unsigned long** est faible.

**Comment by SebCanet** [comment]
Le type long number est rajouté, cela suffit ?
