### ISSUE TITLE
problème de typage avec une boucle "compter avec" (for)

### ISSUE THREAD

**Issue by PhilippeBrangier** [technologiescollege/Blockly-at-rduino#24]
Bonjour, Je rencontre un problème avec la boucle for : la variable choisie est typée par défaut "void"

![1](https://cloud.githubusercontent.com/assets/19346087/15247708/431bf3b4-1916-11e6-9bcd-74eeafc6d2dd.PNG)

code généré : 

```
void i;

void setup() {
  pinMode(i, OUTPUT);
}

void loop() {
  for (i = 1; i <= 10; i=i+1) {
    digitalWrite(i, HIGH);
  }

}
```

ce code ne passe pas la vérification : 

```
Verification failed. Erreur : (sketch file) sketch.ino:1:6: error: variable has incomplete type 'void' void i;      ^
1 error generated.
```

Contournement : 
Je suis obligé de déclarer manuellement la variable ce qui me crée une alerte dans le bloc for : 
![2](https://cloud.githubusercontent.com/assets/19346087/15247926/86fc93f8-1917-11e6-8bb2-443d269f17bd.PNG)

Le code généré passe la vérification : 

```
int i;

void setup() {
    i = (int)(0);

  pinMode(i, OUTPUT);
}

void loop() {
  for (i = 1; i <= 10; i=i+1) {
    digitalWrite(i, HIGH);
  }

}
```

Merci Pour ce logiciel qui me permet d'initier mes enfants à la programmation de façon ludique (projet de robot a base de moteurs de dvd et d'un arduino nano que j'avais en stock), ils ont déjà joué avec scratch et blockly@rduino est parfait pour continuer.

Cordialement

Philippe

**Comment by SebCanet** [comment]
Le typage que j'ai commencé à inotrduire pose des pb autant qu'il en résoud...je planche sur un système qui permet le typage de façon mieux intégrée, mais j'ai peu de temps pour ça...
Bref le meilleur est encore à venir ! :-D

Vraiment content que ça vous plaise et surtout c'est gagné si ça sert à des enfants ! C'est le but premier, je l'ai développé pour l'EducNat pour aussi pour des animateurs non spécialistes et l'éducation populaire : http://www.libreduc.net/

A ce titre je suis preneur pour le blog de tout article/idée de projet facile et pas cher à réaliser pour tous.

Merci.

**Comment by PhilippeBrangier** [comment]
Merci,
  En attendant, pour que mes fils n’aient pas à déclarer leurs variables, j'ai modifié \utils\blocklyDuino.js lignes 371-372 :

```
 case Blockly.Types.NULL.typeName:
      return 'void';
```

en remplaçant void par int,

```
 case Blockly.Types.NULL.typeName:
      return 'int';
```

 Ainsi une variable non typée dans blockly est typée int coté arduino. c'est pas la panacée mais ça me dépanne 
çà ne devrait pas avoir de conséquence néfaste car getArduinoType_ n'est utilisé que pour des variables pour l'instant et le type void n'existe pas pour elles

l'alerte reste, cependant active si l'on type manuellement la variable

Cordialement 

Philippe
