### ISSUE TITLE
Problème d'affectation des pins lors de l'utilisation d'une variable avec le bloc "mettre la broche numérique""

### ISSUE THREAD

**Issue by PhilippeBrangier** [technologiescollege/Blockly-at-rduino#25]
Bonjour ,

 Je rencontre un problème avec le bloc "mettre la broche numérique ... à l'état logique" lorsque je l'utilise avec une variable pour le numéro de broche (tous les blocs de ce type sont susceptibles d'êtres sujets à ce problème) : 
![1](https://cloud.githubusercontent.com/assets/19346087/15248185/1bd1bd18-1919-11e6-8031-c9e3955e36eb.PNG)
le code généré contient "pinMode(MaVariable, OUTPUT);" : 

```
void i;

void setup() {
  pinMode(i, OUTPUT);
}

void loop() {
  for (i = 1; i <= 10; i=i+1) {
    digitalWrite(i, HIGH);
  }

}
```

Mes pins de sortie ne sont donc pas mise en mode "output"

Contournement (j'utilise deux variables pour mettre en lumière les problèmes rencontrés) : 
![3](https://cloud.githubusercontent.com/assets/19346087/15248252/7a61c8aa-1919-11e6-8ab0-48e20aaecba9.PNG)
qui me génère : 

```
int i;
int j;

void setup() {
    i = (int)(1);
  j = (int)(0);
  for (j = 1; j <= 10; j=j+1) {
    pinMode(j, OUTPUT);
  }

  pinMode(i, OUTPUT);
}

void loop() {
  for (i = 1; i <= 10; i=i+1) {
    digitalWrite(i, HIGH);
  }

}
```

Il faut bien penser a initialiser la variable utilisée par le bloc a la valeur d'une des pins utilisée en sortie sinon elle vaut 0 et c'est donc la pin 0 qui est passée a "output"

Je n'ai pas trouvé de bloc pour l'affectation des pins, je suis donc passé par un bloc "ligne de code"

suggestions : 
- Ce bloc ne devrait pas tenter d'affecter des pins si l'argument est une variable 
- Un bloc permettant l'affectation des pins pourrait être créé pour éviter l'utilisation du bloc "ligne de code"

Cordialement 

Philippe

**Comment by SebCanet** [comment]
Un bloc permettant l'affectation des pins pourrait être créé pour éviter l'utilisation du bloc "ligne de code" me semble une bonne idée, à rajouter donc...

**Comment by SebCanet** [comment]
Fixé....merci.
![image 1](https://user-images.githubusercontent.com/6362199/35541239-1b021c6e-055a-11e8-9d14-627cb7dd36cd.jpg)
