### ISSUE TITLE
What about libraries ?

### ISSUE THREAD

**Issue by jm4r7in** [technologiescollege/Blockly-at-rduino#29]
Hello,
Is it possible to include librairies which are not supported by CodeBender ?
Thanks a lot !
Jerome

**Comment by SebCanet** [comment]
Soon...
We're working on an offline uploader, in which you would be able to put your own librairies.

**Comment by SebCanet** [comment]
The offline uploader is finished !
It uses "rDuino-uploader": [https://github.com/nbremond77/rDuino-Compiler-Uploader-Server](https://github.com/nbremond77/rDuino-Compiler-Uploader-Server) to send code to local Arduino IDE ; but works only for Windows and made to be usable for kids:
[Blockly@rduino-communication](https://github.com/technologiescollege/Blockly-rduino-communication)
