### ISSUE TITLE
add 28BYJ-48 Stepper Motor with ULN2003 driver

### ISSUE THREAD

**Issue by SebCanet** [technologiescollege/Blockly-at-rduino#48]
References:
[http://42bots.com/tutorials/28byj-48-stepper-motor-with-uln2003-driver-and-arduino-uno/](http://42bots.com/tutorials/28byj-48-stepper-motor-with-uln2003-driver-and-arduino-uno/)
[http://tiptopboards.free.fr/arduino_forum/viewtopic.php?f=2&t=41](http://tiptopboards.free.fr/arduino_forum/viewtopic.php?f=2&t=41)
[http://www.geeetech.com/wiki/index.php/Stepper_Motor_5V_4-Phase_5-Wire_%26_ULN2003_Driver_Board_for_Arduino](http://www.geeetech.com/wiki/index.php/Stepper_Motor_5V_4-Phase_5-Wire_%26_ULN2003_Driver_Board_for_Arduino)

**Comment by openelearning** [comment]
à voir donc si je pourrai ajouter un bloc pour ce moteur pas à pas. Dans https://github.com/technologiescollege/Blockly-at-rduino/issues/141#issuecomment-450011215 tu indiques "je veux bien que tu me donnes une référence + lien pour le helpUrl + photo."
Je vais donc essayer de les appliquer pour ici.
1) Il y a déjà 3 références ci-dessus, ce n'est donc plus la peine, non ?
2) un lien pour le help url : désolé je ne sais pas ce que sait (je débarque dans blockly at arduino :) ) tu sais s'il y a des exemples d'help url pour que je vois ce que c'est (un tuto sur l'utilisation du bloc ?)  ?
3) pour la photo ok, j'en prendrai ou j'en trouverai compatible avec la GNU/GPL.

**Comment by openelearning** [comment]
2) ok pour le help url, je viens de comprendre, c'est le lien qui sera proposé quand on fait un clic droit sur le bloc > aide.

**Comment by SebCanet** [comment]
1. Pour ton bloc que tu désires créer, il s'agit bien du contrôleur ULN2003 ?
2. impeccable
3. c'est vrai que je ne suis pas trop dans les clous à ce niveau là....pas le temps d'être précis malheureusement.

**Comment by openelearning** [comment]
1. En fait c'est le ULN2003A, je ne sais s'il y a une différence avec ULN2003.
3. Oui pas évident la gestion des licences... Pas trouvé de photos sous licence libre, mais j'ai pu trouvé pour le moment un bel SVG représentatif issu du domaine public (openclipart) dont j'ai mentionné la licence et le lien dans le code (en cours d'écriture).

**Comment by SebCanet** [comment]
Zou c'est bouclé ! Merci.

**Comment by SebCanet** [comment]
Still few problems...

**Comment by tutoblockly** [comment]
Quand on colle les 2 blocs de déclaration, il y a un code qui disparaît.

**Comment by tutoblockly** [comment]
Problème corrigé (il fallait ajouter un return ''; à la fin du bloc de config).

**Comment by SebCanet** [comment]
C'est bouclé grâce à ta mise à jour d'hier ?

**Comment by tutoblockly** [comment]
Oui je n'ai plus le problème indiqué (cela a peut-être été corrigé via un commit précédent cependant) et le moteur semble bien fonctionner avec le code. Il me reste juste à priori à externaliser la traduction.

**Comment by SebCanet** [comment]
Super, merci ! On cloture.
