### ISSUE TITLE
add Blynk blocks

### ISSUE THREAD

**Issue by SebCanet** [technologiescollege/Blockly-at-rduino#55]
add blocks https://github.com/makewitharduino/BlocklyDuino

**Comment by ghost** [comment]
Hello, 
Mr_leroy alias Yorelk on Github
je viens de créer un fork  de Blockly-at-duino, et viens de poster mes réorganisation de la blibliothéque Blynk.
https://github.com/yorelk/Blockly-at-rduino

Bonne Journée

**Comment by SebCanet** [comment]
Bonjour,
en comparant les 2 versions Github ne me signale pas de différence ??!
Si tu actives les pages perso de Github tu peux afficher directement le résultat en ligne comme je le fais avec http://technologiescollege.github.io/Blockly-at-rduino/

**Comment by ghost** [comment]
Je veux bien mais on fait comment je suis un peu neux neux avec github... lolo

**Comment by SebCanet** [comment]
Moi non plus je ne suis pas à l'aise dès qu'il signale un pb...
J'utilise le client de synchro officiel : https://desktop.github.com/
Sinon tu as SourceTree qui est très bien : https://fr.atlassian.com/software/sourcetree
Je te conseille de pas mal jouer avec pour être sûr d'avoir compris le fonctionnement, j'ai déjà perdu quelques données au début...ensuite la mécanique est de valider (commit) une modification, puis de la remonter (push) ou bien de la récupérer depuis le web (pull). Tu peux aussi faire la même chose d'un dépôt (version sur le web) vers un autre.

**Comment by tech-rostand** [comment]
Mr_leroy
Nouveaux comptes pour le collège donc j'en profite pour scinder mes activités.
Bon logiquement tu devrais avoir accés a ma version en ligne sur 
https://tech-rostand.github.io/ créer a partir d'un fork.
Amicalement

**Comment by tech-rostand** [comment]
Mr_leroy bis
Bon j'ai enfin compris le principe.
J'ai donc crée un nouveaux compte lié à mes activités du collège...
Créer un Fork  tech-rostand
Publier sur le web https://tech-rostand.github.io/Blockly-at-arduino/
Et poussé mais changements.
;-)

**Comment by SebCanet** [comment]
Super ! J'ai vu des modifs de Blynk déjà. Quand tu penses avoir fait le tour des fonctions, on verra pour faire un push ou pull d'une version sur l'autre. Merci.

**Comment by SebCanet** [comment]
J'ai fait une requête de pull pour récupérer ta version comportant les modifs pour Blynk.
Dis moi si c'est ok ou si tu veux que j'annule. N'hésite pas à m'en proposer d'autres.
Merci de ton travail.

**Comment by tech-rostand** [comment]
Salut c’est encore une version légère, je suis en vacance depuis 3semaines et j’ai pas avancé beaucoup. Mais cela est fonctionnel pour des essais de bases.

 

Je reprends la dev dès que mon planning s’éclaircit.

 

A bientôt. 

 

De : SebCanet [mailto:notifications@github.com] 
Envoyé : mardi 29 août 2017 13:45
À : technologiescollege/Blockly-at-rduino <Blockly-at-rduino@noreply.github.com>
Cc : Mr_Leroy <tech.rostand@gmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [technologiescollege/Blockly-at-rduino] add Blynk blocks (#55)

 

J'ai fait une requête de pull pour récupérer ta version comportant les modifs pour Blynk.
Dis moi si c'est ok ou si tu veux que j'annule.
Merci de ton travail.

**Comment by SebCanet** [comment]
Pas de souci, ça m'a aussi permis de tester la fonction pull d'un dépôt à l'autre.
Comme ça je pourrai intégrer tes améliorations eau fur et à mesure.
Bonne reprise !
