### ISSUE TITLE
how i can use  " arduino ir remote control "

### ISSUE THREAD

**Issue by hamam1** [technologiescollege/Blockly-at-rduino#80]
please can you help me how i can use " arduino ir remote control "
sincerely <3 <3 <3 <3 <3

**Comment by SebCanet** [comment]
It's explained there : [http://www.instructables.com/id/The-Easiest-Way-to-Use-Any-IR-Remote-with-Ardiuno/](http://www.instructables.com/id/The-Easiest-Way-to-Use-Any-IR-Remote-with-Ardiuno/)

**Comment by hamam1** [comment]
i can't write pin Num

![screenshot-2017-9-30 blockly rduino](https://user-images.githubusercontent.com/32391090/31047044-bac2d7d6-a603-11e7-9b79-8dd1e6a718f6.png)

**Comment by SebCanet** [comment]
You did not declare a board before ?

**Comment by hamam1** [comment]
sorry ! what you are mean ?

**Comment by SebCanet** [comment]
Go to the red button on the top left, "global configuration" dans choose card first.
