### ISSUE TITLE
Traduction bluetooth block in french

### ISSUE THREAD

**Issue by jbet** [technologiescollege/Blockly-at-rduino#9]
Bloc bluetooh est mal traduit en français.
![selection_155](https://cloud.githubusercontent.com/assets/5906988/14157213/585d70cc-f6ca-11e5-9aeb-dbb2c8dec42b.png)
Voici sa traduction en espagnol
![selection_156](https://cloud.githubusercontent.com/assets/5906988/14157243/6d64a954-f6ca-11e5-9512-50c8fb570d9a.png)

Donc il faudrait changer lire par envoyer.

**Comment by SebCanet** [comment]
c'est déjà fait ! de peu...
merci
